config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, except: [:destroy] do 
    resources :doses, only: [:create]
  end

  resources :doses, only:[:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    validates :name, uniqueness: true, presence: true
    has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates  :ingredient_id, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    has_many :cocktails
    validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_cocktails

    private

    def set_cocktails
        @cocktails = Cocktail.all
    end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

    before_action :set_cocktail, only: [:show, :edit, :update]

    def index
        @cocktails = Cocktail.all
    end

    def show
        @dose = Dose.new
    end

    def new
        @cocktail = Cocktail.new
    end

    def create
        @cocktail = Cocktail.new(cocktail_params)
        if @cocktail.save
            redirect_to @cocktail, notice: 'Cocktail was successfully created.'
          else
            render :new
          end
    end

    def update
        if @cocktail.update(cocktail_params)
          redirect_to @cocktail, notice: 'Cocktail was successfully updated.'
        else
          render :edit
        end
      end

    private

    def set_cocktail
        @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
        params.require(:cocktail).permit(:name, :image_url, :photo)
    end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

    def create
        @dose = Dose.new(dose_params)
        @cocktail = Cocktail.find(params[:cocktail_id])
        unless @dose.ingredient_id.nil?
            @ingredient = Ingredient.find(@dose.ingredient_id)
        end

        @dose.cocktail =  @cocktail
        @dose.ingredient = @ingredient

        if @dose.save
            redirect_to cocktail_path(@cocktail)
        else
            render "cocktails/show"
        end
    end

    def destroy
        @dose = Dose.find(params[:id])
        @dose.destroy
        redirect_to cocktail_path(@dose.cocktail)
    end
    


    private

    def dose_params
        params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
    end
    
end






  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
    <div class="card p-3">
      <%= simple_form_for(cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>
    </div>
  

app/views/cocktails/edit.html.erb
<h1>Edit <%= @cocktail.name %></h1>
<div class="row">
  <div class="col-6">
    <%= render "form", cocktail: @cocktail %>
  </div>
  <div class="col-6">
    <div class="card">
        <img class= "img-fluid" src="<%=@cocktail.image_url%>" alt="">
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="row">
  <div class="banner">
    <div class="container">
      <h1>Cocktails List</h1>
    </div>
  </div>
</div>


  

<div class="row">
    <%@cocktails.each do |cocktail| %>
    <div class="col-4 ">
      <div class="card border-light mb-3" style="width: 18rem;">
      <%unless cocktail.photo.attachment.nil?%>
        <%= cl_image_tag cocktail.photo.key, alt: "Card image", class: "card-img-top image-card-size" %>
      <%end  %>
        <div class="card-body">
          <h5 class="card-title text-center"><%= cocktail.name %></h5>
          <div class = "d-flex justify-content-between">
          <div>
          <%= link_to cocktail_path(cocktail), class:"text-success" do%>
          See details <i class="far fa-eye text-success"></i>
          <%end %> 
               
          </div>
          <div>
          <%= link_to "Edit",edit_cocktail_path(cocktail), class:"text-warning"%> <i class="fas fa-pen text-warning"></i>
          </div>
          </div>
          
        </div>
      </div>
      </div>
    <% end  %>
  
</div>

app/views/cocktails/new.html.erb
<h1 class="text-white">Create a cocktail</h1>
<%= render "form", cocktail: @cocktail %>

app/views/cocktails/show.html.erb
<h1 class = "text-white"><%= @cocktail.name %></h1>
<div class="row align-items-center">
  <div class="col-6">
    <div class="card" style="width: 18rem;">
    <%unless @cocktail.photo.attachment.nil?%>
      <%= cl_image_tag @cocktail.photo.key, class: "card-img-top image-card-size" %>
    <%end %>
      <div class="card-body">
        <h5 class="card-title"><%= @cocktail.name %></h5>
        <p class="card-text">
        <%cocktail_id = @cocktail.id %>
        <%@doses = Dose.where(cocktail_id: cocktail_id) %>
        <% @doses.all.each do |dose| %>
          <%= dose.description %> <%= dose.ingredient.name %>
          <%= link_to dose_path(dose), method: :delete do %>
                            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
          <br>
        <%end %>
      </div>
    </div>
  </div>




  <div class="col-6">
    <div class="card p-3" style="width: 18rem;">
      <div class="h4">Add ingredient</div>
        <%= simple_form_for [ @cocktail, @dose ] do |f| %>
          <%= f.input :description %>
          <%= f.association :ingredient %>
          <%= f.submit "Add ", class: "btn btn-primary" %>
        <% end %>
      </div>
  </div>
</div>

<%= link_to "Back to all cocktails",cocktails_path, class: "text-white"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  
  </head>

  <body class = "bg-dark">

    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <a class="navbar-brand" href="#">
        <div class="h1">
        <%= link_to "Youpi cocktail",cocktails_path, class: "text-secondary"%>
        <i class="fas fa-cocktail"></i>
        </div>
      </a>
        
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Choose a cocktail
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">     
          <% @cocktails.each do |cocktail| %>
            <%= link_to cocktail.name, cocktail_path(cocktail), class:"dropdown-item" %>
          <% end %>
          </div>
        </li>
      </ul>
        <%= link_to "Add a new cocktail",new_cocktail_path, class:"nav-link btn btn-secondary" %>
    </div>
  </nav>

    <div class="background-color-grey container-min-height">
      <div class="container pt-3">
        <%= yield %>
      </div>
    </div>
    
  </body>
</html>